apiVersion: v1
kind: Pod
spec:
  containers:
  - name: awscli
    image: angelodias/awscli:latest
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
  volumes:
  - name: varlibcontainers
    emptyDir:
